### ISSUE TITLE
MSBuild.exe not found for ToolsVersion 15.0 and MSBuild BuildTools 15.0 & VS2019 installed 

### ISSUE THREAD

**Issue by dejoost** [fluffynuts/gulp-msbuild#3]
On my machine I have both BuildTools 15.0 and VS 2019 enterprise installed, when I try to build with ToolsVersion = 15.0 I get following error: 
Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\amd64\MSBuild.exe ENOENT

Problem seems to be in the msbuild-finder.js file. vswhere returns " C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" and then the "15.0" subfolders are added. It should instead be "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" (probably similar issue for VS2017 side-by-side installs with vs2019).

Some background info: I need this setup since our CI/CD i still configured for 15.0 buildtools.

**Comment by fluffynuts** [comment]
Hi @dejoost ! Apologies for the incredibly late response: I haven't seen a notification for this until now. Slack, I know. Is this still an issue? If it is, I'd really like to resolve it. If you've moved on and found a different route, I apologise for the inconvenience ):

**Comment by dejoost** [comment]
Better late then never :-). In the meantime we switched to the dotnet client. So we no longer need this fix.

**Comment by fluffynuts** [comment]
Ah, ok. I have a repo I use as a submodule which can switch between the two. I'm currently working on converting it to an npm module so one could basically 'npx zarro build-dotnet' or 'npx zarro test-dotnet'. So for me, ensuring both work is of importance. 

I'm sorry I responded so late that you had to switch.
