### ISSUE TITLE
Unable to build a project using Visual Studio 2017 while having VS 2019 installed

### ISSUE THREAD

**Issue by MikeAlhayek** [fluffynuts/gulp-msbuild#5]
First of all, thank you for this very helpful project and your clean code.

I have both Visual Studio 2017 along with Visual Studio 2019 installed on my machine. I have a project that I need to build it using MBbuild found in the VS 2017, not VS 2019.

Here is the configuration I am using 
```
msbuild({
            toolsVersion: 15.0,
            properties: {
                Configuration: 'Release',
                verbosity: 'minimal'
            },
            targets: ['Clean', 'Build'],
            errorOnFail: true,
            stdout: true
        })
```

Looking at your code, I can see where you are forcing the looking to using [/Microsoft Visual Studio Installer/vswhere.exe](https://github.com/fluffynuts/gulp-msbuild/blob/master/lib/msbuild-finder.js#L54-L57)

I would think the code on line [54-57](https://github.com/fluffynuts/gulp-msbuild/blob/master/lib/msbuild-finder.js#L54-L57) should not be part of the `detectMsBuild15Dir` method and should only be part of the call [autoDetectVersion()](https://github.com/fluffynuts/gulp-msbuild/blob/master/lib/msbuild-finder.js#L134) method.

**Comment by fluffynuts** [comment]
I've manually merged into my master (there was a failing test and a conflict). I've done a beta release (0.7.1) -- so please try this out with `npm install --save-dev gulp-msbuild@beta` and report back to me. I'm not the original author of gulp-msbuild, but I'm committed to maintaining it. I see it in daily use (tens to perhaps a hundred times), so I'll update a few of my dependent projects to the beta as well -- the best test for this is probably the trial-by-fire method (: Once the beta is verified as "probably not breaking things", I'll do a non-beta release (would be 0.8.0)

Thanks for raising the issue and providing a PR!

Apologies for taking so long to respond to this -- two weeks is a long time. I'd like to be quicker about it -- I didn't see any notifications via GitHub (perhaps lost in the sea of notifications) -- just happened to check up where issues are surfaced on the npmjs page.

Please fee free to tweet me (@fux0r) in the future, if you have more contributions you'd like to make and I'm taking > 2 days (:

**Comment by MikeAlhayek** [comment]
@fluffynuts I tried the update and it seems to be working as expected. Thanks you for this update!
