### ISSUE TITLE
gulp-msbuild has moved

### ISSUE THREAD

**Issue by thany** [fluffynuts/gulp-msbuild#7]
It says in the README

> gulp-msbuild has moved

To where? Please specify.

**Comment by fluffynuts** [comment]
hi @thany

apologies for the late response - i must have missed the notification

`gulp-msbuild` has moved _here_ from [the original github project](https://github.com/hoffi/gulp-msbuild) - the mention in the README is an error on my part - I obviously didn't remove that ): I'll do so soon though (:
